title: <p align="center">Madhusmita Ghosh</p>
logo: /assets/img/logo.png
description: 
    <p align="center">

   <a href="https://github.com/madhusmita6">GitHub</a>
   </p>
theme: jekyll-theme-minimal
